version: '3.8'

services:
  #################################
  #             Nginx             #
  #################################
  nginx:
    image: nginx:latest
    container_name: nginx-prestashop
    ports:
      - "80:80"           # Nginx will expose port 80 to the host system
      - "443:443"         # Nginx will expose port 443 to the host system
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro    # Use the Nginx config from the nginx directory
      - ./app:/var/www/html
      - ./nginx/ssl:/etc/ssl/                              # Mount the app folder containing PrestaShop into the container
    depends_on:
      - php
    restart: always

 
  #################################
  #             PHP8.1            #
  ################################# 
  php:
    container_name: php-prestashop
    
    build:
      context: .
      dockerfile: php8 .2Dockerfile
    volumes:
      - ./app:/var/www/html                              # Mount the app folder containing PrestaShop into the container
      - ./php/php.ini:/usr/local/etc/php/php.ini          
    ports:
      - "9000:9000"
  
    depends_on:
      - mysql
    restart: always
    entrypoint: ["/bin/sh", "-c", "chown -R www-data:www-data /var/www/html && chmod -R 777 /var/www/html && php-fpm"]

  # php2:
  #   container_name: php-prestashop-2
    
  #   build:
  #     context: .
  #     dockerfile: php8.1Dockerfile
  #   volumes:
  #     - ./app:/var/www/html                              # Mount the app folder containing PrestaShop into the container
  #     - ./php/php.ini:/usr/local/etc/php/php.ini          
  #   ports:
  #     - "9002:9000"
  
  #   depends_on:
  #     - mysql
  #   restart: always
  #   entrypoint: ["/bin/sh", "-c", "chown -R www-data:www-data /var/www/html && chmod -R 777 /var/www/html && php-fpm"]

  #################################
  #             MySQL 5.7         #
  #################################
  mysql:
    image: mysql:5.7
    container_name: mysql-prestashop
    ports:
      - "3306:3306"
    
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: prestashop
      MYSQL_USER: prestashop
      MYSQL_PASSWORD: password
    volumes:
      - ./mysql/data:/var/lib/mysql                     # Persist MySQL data into the mysql directory
    restart: always
  

  #################################
  #         PhpMyAdmin            #
  #################################
  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   container_name: phpmyadmin-prestashop
  #   links:
  #     - mysql-prestashop
  #   ports:
  #     - 8081:80
  #   environment:
  #     PMA_HOST: mysql-prestashop
  #     PMA_PORT: 3306
  #     PMA_ARBITRARY: 1
  #   volumes:
  #     - ./mysql/data:/var/lib/mysql                     # Persist MySQL data into the mysql directory
  #   restart: always
    
    
volumes:
  mysql_data:
